name : Build and Deploy Admin Service to Render

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name : Checkout code
        uses : actions/checkout@v4

      - name : Set up Bun
        uses : oven-sh/setup-bun@v1

      - name : Install dependencies
        run : bun Install

      - name : Build Admin Service
        run : bun build

      - name : Deploy to Render
        run : curl -X POST ${{secrets.RENDER_DEPLOY_HOOK}}


    